// Generates src/lib/telligence/abi.ts from the compiled Foundry artifact, so the
// frontend ABI can never drift from the deployed contract. Run after forge build.
import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const artifact = resolve(here, "../../out/TelligenceDeployer.sol/TelligenceDeployer.json");
const out = resolve(here, "../src/lib/telligence/abi.ts");

const { abi } = JSON.parse(readFileSync(artifact, "utf8"));
if (!Array.isArray(abi) || !abi.some((f) => f.name === "startEngine")) {
  throw new Error("artifact has no startEngine — run `forge build` at the repo root first");
}

mkdirSync(dirname(out), { recursive: true });
writeFileSync(
  out,
  `// GENERATED by scripts/gen-abi.mjs from out/TelligenceDeployer.sol/TelligenceDeployer.json.
// Do not edit by hand: run \`npm run gen:abi\` after changing the contract.

export const telligenceDeployerAbi = ${JSON.stringify(abi, null, 2)} as const;
`,
);
console.log(`wrote ${out} (${abi.length} entries)`);
