// GENERATED by scripts/gen-abi.mjs from out/PluginDeployer.sol/PluginDeployer.json.
// Do not edit by hand: run `npm run gen:abi` after changing the contract.

export const pluginDeployerAbi = [
  {
    "type": "constructor",
    "inputs": [
      {
        "name": "revDeployer",
        "type": "address",
        "internalType": "contract IREVDeployerMinimal"
      },
      {
        "name": "accountingContexts",
        "type": "tuple[]",
        "internalType": "struct JBAccountingContext[]",
        "components": [
          {
            "name": "token",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "decimals",
            "type": "uint8",
            "internalType": "uint8"
          },
          {
            "name": "currency",
            "type": "uint32",
            "internalType": "uint32"
          }
        ]
      }
    ],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "ALLOW_SUCKER_DEPLOYMENT",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint16",
        "internalType": "uint16"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "CASH_OUT_TAX_RATE",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint16",
        "internalType": "uint16"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "INITIAL_ISSUANCE",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint112",
        "internalType": "uint112"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "ISSUANCE_HALVING",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint32",
        "internalType": "uint32"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "REV_DEPLOYER",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address",
        "internalType": "contract IREVDeployerMinimal"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "accountingContexts",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "tuple[]",
        "internalType": "struct JBAccountingContext[]",
        "components": [
          {
            "name": "token",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "decimals",
            "type": "uint8",
            "internalType": "uint8"
          },
          {
            "name": "currency",
            "type": "uint32",
            "internalType": "uint32"
          }
        ]
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "doublingSeconds",
    "inputs": [
      {
        "name": "doubling",
        "type": "uint8",
        "internalType": "enum PluginDoubling"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "uint32",
        "internalType": "uint32"
      }
    ],
    "stateMutability": "pure"
  },
  {
    "type": "function",
    "name": "houseConfig",
    "inputs": [
      {
        "name": "machine",
        "type": "tuple",
        "internalType": "struct PluginMachine",
        "components": [
          {
            "name": "name",
            "type": "string",
            "internalType": "string"
          },
          {
            "name": "id",
            "type": "string",
            "internalType": "string"
          },
          {
            "name": "pitchUri",
            "type": "string",
            "internalType": "string"
          },
          {
            "name": "machine",
            "type": "address",
            "internalType": "address payable"
          },
          {
            "name": "keep",
            "type": "uint8",
            "internalType": "enum PluginKeep"
          },
          {
            "name": "doubling",
            "type": "uint8",
            "internalType": "enum PluginDoubling"
          },
          {
            "name": "startsAtOrAfter",
            "type": "uint48",
            "internalType": "uint48"
          },
          {
            "name": "salt",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "routes",
            "type": "tuple[]",
            "internalType": "struct PluginRoute[]",
            "components": [
              {
                "name": "projectId",
                "type": "uint64",
                "internalType": "uint64"
              },
              {
                "name": "percentOfKeep",
                "type": "uint16",
                "internalType": "uint16"
              },
              {
                "name": "locked",
                "type": "bool",
                "internalType": "bool"
              }
            ]
          }
        ]
      }
    ],
    "outputs": [
      {
        "name": "configuration",
        "type": "tuple",
        "internalType": "struct REVConfig",
        "components": [
          {
            "name": "description",
            "type": "tuple",
            "internalType": "struct REVDescription",
            "components": [
              {
                "name": "name",
                "type": "string",
                "internalType": "string"
              },
              {
                "name": "ticker",
                "type": "string",
                "internalType": "string"
              },
              {
                "name": "uri",
                "type": "string",
                "internalType": "string"
              },
              {
                "name": "salt",
                "type": "bytes32",
                "internalType": "bytes32"
              }
            ]
          },
          {
            "name": "baseCurrency",
            "type": "uint32",
            "internalType": "uint32"
          },
          {
            "name": "operator",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "scopeCashOutsToLocalBalances",
            "type": "bool",
            "internalType": "bool"
          },
          {
            "name": "stageConfigurations",
            "type": "tuple[]",
            "internalType": "struct REVStageConfig[]",
            "components": [
              {
                "name": "startsAtOrAfter",
                "type": "uint48",
                "internalType": "uint48"
              },
              {
                "name": "autoIssuances",
                "type": "tuple[]",
                "internalType": "struct REVAutoIssuance[]",
                "components": [
                  {
                    "name": "chainId",
                    "type": "uint32",
                    "internalType": "uint32"
                  },
                  {
                    "name": "count",
                    "type": "uint104",
                    "internalType": "uint104"
                  },
                  {
                    "name": "beneficiary",
                    "type": "address",
                    "internalType": "address"
                  }
                ]
              },
              {
                "name": "splitPercent",
                "type": "uint16",
                "internalType": "uint16"
              },
              {
                "name": "splits",
                "type": "tuple[]",
                "internalType": "struct JBSplit[]",
                "components": [
                  {
                    "name": "percent",
                    "type": "uint32",
                    "internalType": "uint32"
                  },
                  {
                    "name": "projectId",
                    "type": "uint64",
                    "internalType": "uint64"
                  },
                  {
                    "name": "beneficiary",
                    "type": "address",
                    "internalType": "address payable"
                  },
                  {
                    "name": "preferAddToBalance",
                    "type": "bool",
                    "internalType": "bool"
                  },
                  {
                    "name": "lockedUntil",
                    "type": "uint48",
                    "internalType": "uint48"
                  },
                  {
                    "name": "hook",
                    "type": "address",
                    "internalType": "contract IJBSplitHook"
                  }
                ]
              },
              {
                "name": "initialIssuance",
                "type": "uint112",
                "internalType": "uint112"
              },
              {
                "name": "issuanceCutFrequency",
                "type": "uint32",
                "internalType": "uint32"
              },
              {
                "name": "issuanceCutPercent",
                "type": "uint32",
                "internalType": "uint32"
              },
              {
                "name": "cashOutTaxRate",
                "type": "uint16",
                "internalType": "uint16"
              },
              {
                "name": "extraMetadata",
                "type": "uint16",
                "internalType": "uint16"
              }
            ]
          }
        ]
      }
    ],
    "stateMutability": "pure"
  },
  {
    "type": "function",
    "name": "keepPercent",
    "inputs": [
      {
        "name": "keep",
        "type": "uint8",
        "internalType": "enum PluginKeep"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "uint16",
        "internalType": "uint16"
      }
    ],
    "stateMutability": "pure"
  },
  {
    "type": "function",
    "name": "startEngine",
    "inputs": [
      {
        "name": "machine",
        "type": "tuple",
        "internalType": "struct PluginMachine",
        "components": [
          {
            "name": "name",
            "type": "string",
            "internalType": "string"
          },
          {
            "name": "id",
            "type": "string",
            "internalType": "string"
          },
          {
            "name": "pitchUri",
            "type": "string",
            "internalType": "string"
          },
          {
            "name": "machine",
            "type": "address",
            "internalType": "address payable"
          },
          {
            "name": "keep",
            "type": "uint8",
            "internalType": "enum PluginKeep"
          },
          {
            "name": "doubling",
            "type": "uint8",
            "internalType": "enum PluginDoubling"
          },
          {
            "name": "startsAtOrAfter",
            "type": "uint48",
            "internalType": "uint48"
          },
          {
            "name": "salt",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "routes",
            "type": "tuple[]",
            "internalType": "struct PluginRoute[]",
            "components": [
              {
                "name": "projectId",
                "type": "uint64",
                "internalType": "uint64"
              },
              {
                "name": "percentOfKeep",
                "type": "uint16",
                "internalType": "uint16"
              },
              {
                "name": "locked",
                "type": "bool",
                "internalType": "bool"
              }
            ]
          }
        ]
      },
      {
        "name": "suckers",
        "type": "tuple",
        "internalType": "struct REVSuckerDeploymentConfig",
        "components": [
          {
            "name": "deployerConfigurations",
            "type": "tuple[]",
            "internalType": "struct JBSuckerDeployerConfig[]",
            "components": [
              {
                "name": "deployer",
                "type": "address",
                "internalType": "contract IJBSuckerDeployer"
              },
              {
                "name": "peer",
                "type": "bytes32",
                "internalType": "bytes32"
              },
              {
                "name": "mappings",
                "type": "tuple[]",
                "internalType": "struct JBTokenMapping[]",
                "components": [
                  {
                    "name": "localToken",
                    "type": "address",
                    "internalType": "address"
                  },
                  {
                    "name": "minGas",
                    "type": "uint32",
                    "internalType": "uint32"
                  },
                  {
                    "name": "remoteToken",
                    "type": "bytes32",
                    "internalType": "bytes32"
                  }
                ]
              }
            ]
          },
          {
            "name": "salt",
            "type": "bytes32",
            "internalType": "bytes32"
          }
        ]
      }
    ],
    "outputs": [
      {
        "name": "revnetId",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "stateMutability": "payable"
  },
  {
    "type": "function",
    "name": "storeConfig",
    "inputs": [
      {
        "name": "machine",
        "type": "tuple",
        "internalType": "struct PluginMachine",
        "components": [
          {
            "name": "name",
            "type": "string",
            "internalType": "string"
          },
          {
            "name": "id",
            "type": "string",
            "internalType": "string"
          },
          {
            "name": "pitchUri",
            "type": "string",
            "internalType": "string"
          },
          {
            "name": "machine",
            "type": "address",
            "internalType": "address payable"
          },
          {
            "name": "keep",
            "type": "uint8",
            "internalType": "enum PluginKeep"
          },
          {
            "name": "doubling",
            "type": "uint8",
            "internalType": "enum PluginDoubling"
          },
          {
            "name": "startsAtOrAfter",
            "type": "uint48",
            "internalType": "uint48"
          },
          {
            "name": "salt",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "routes",
            "type": "tuple[]",
            "internalType": "struct PluginRoute[]",
            "components": [
              {
                "name": "projectId",
                "type": "uint64",
                "internalType": "uint64"
              },
              {
                "name": "percentOfKeep",
                "type": "uint16",
                "internalType": "uint16"
              },
              {
                "name": "locked",
                "type": "bool",
                "internalType": "bool"
              }
            ]
          }
        ]
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "tuple",
        "internalType": "struct REVDeploy721TiersHookConfig",
        "components": [
          {
            "name": "baseline721HookConfiguration",
            "type": "tuple",
            "internalType": "struct REVBaseline721HookConfig",
            "components": [
              {
                "name": "name",
                "type": "string",
                "internalType": "string"
              },
              {
                "name": "symbol",
                "type": "string",
                "internalType": "string"
              },
              {
                "name": "baseUri",
                "type": "string",
                "internalType": "string"
              },
              {
                "name": "tokenUriResolver",
                "type": "address",
                "internalType": "contract IJB721TokenUriResolver"
              },
              {
                "name": "contractUri",
                "type": "string",
                "internalType": "string"
              },
              {
                "name": "tiersConfig",
                "type": "tuple",
                "internalType": "struct JB721InitTiersConfig",
                "components": [
                  {
                    "name": "tiers",
                    "type": "tuple[]",
                    "internalType": "struct JB721TierConfig[]",
                    "components": [
                      {
                        "name": "price",
                        "type": "uint104",
                        "internalType": "uint104"
                      },
                      {
                        "name": "initialSupply",
                        "type": "uint32",
                        "internalType": "uint32"
                      },
                      {
                        "name": "votingUnits",
                        "type": "uint32",
                        "internalType": "uint32"
                      },
                      {
                        "name": "reserveFrequency",
                        "type": "uint16",
                        "internalType": "uint16"
                      },
                      {
                        "name": "reserveBeneficiary",
                        "type": "address",
                        "internalType": "address"
                      },
                      {
                        "name": "encodedIpfsUri",
                        "type": "bytes32",
                        "internalType": "bytes32"
                      },
                      {
                        "name": "category",
                        "type": "uint24",
                        "internalType": "uint24"
                      },
                      {
                        "name": "discountPercent",
                        "type": "uint8",
                        "internalType": "uint8"
                      },
                      {
                        "name": "flags",
                        "type": "tuple",
                        "internalType": "struct JB721TierConfigFlags",
                        "components": [
                          {
                            "name": "allowOwnerMint",
                            "type": "bool",
                            "internalType": "bool"
                          },
                          {
                            "name": "useReserveBeneficiaryAsDefault",
                            "type": "bool",
                            "internalType": "bool"
                          },
                          {
                            "name": "transfersPausable",
                            "type": "bool",
                            "internalType": "bool"
                          },
                          {
                            "name": "useVotingUnits",
                            "type": "bool",
                            "internalType": "bool"
                          },
                          {
                            "name": "cantBeRemoved",
                            "type": "bool",
                            "internalType": "bool"
                          },
                          {
                            "name": "cantIncreaseDiscountPercent",
                            "type": "bool",
                            "internalType": "bool"
                          },
                          {
                            "name": "cantBuyWithCredits",
                            "type": "bool",
                            "internalType": "bool"
                          }
                        ]
                      },
                      {
                        "name": "splitPercent",
                        "type": "uint32",
                        "internalType": "uint32"
                      },
                      {
                        "name": "splits",
                        "type": "tuple[]",
                        "internalType": "struct JBSplit[]",
                        "components": [
                          {
                            "name": "percent",
                            "type": "uint32",
                            "internalType": "uint32"
                          },
                          {
                            "name": "projectId",
                            "type": "uint64",
                            "internalType": "uint64"
                          },
                          {
                            "name": "beneficiary",
                            "type": "address",
                            "internalType": "address payable"
                          },
                          {
                            "name": "preferAddToBalance",
                            "type": "bool",
                            "internalType": "bool"
                          },
                          {
                            "name": "lockedUntil",
                            "type": "uint48",
                            "internalType": "uint48"
                          },
                          {
                            "name": "hook",
                            "type": "address",
                            "internalType": "contract IJBSplitHook"
                          }
                        ]
                      }
                    ]
                  },
                  {
                    "name": "currency",
                    "type": "uint32",
                    "internalType": "uint32"
                  },
                  {
                    "name": "decimals",
                    "type": "uint8",
                    "internalType": "uint8"
                  }
                ]
              },
              {
                "name": "flags",
                "type": "tuple",
                "internalType": "struct REV721TiersHookFlags",
                "components": [
                  {
                    "name": "noNewTiersWithReserves",
                    "type": "bool",
                    "internalType": "bool"
                  },
                  {
                    "name": "noNewTiersWithVotes",
                    "type": "bool",
                    "internalType": "bool"
                  },
                  {
                    "name": "noNewTiersWithOwnerMinting",
                    "type": "bool",
                    "internalType": "bool"
                  },
                  {
                    "name": "preventOverspending",
                    "type": "bool",
                    "internalType": "bool"
                  }
                ]
              }
            ]
          },
          {
            "name": "salt",
            "type": "bytes32",
            "internalType": "bytes32"
          },
          {
            "name": "preventOperatorAdjustingTiers",
            "type": "bool",
            "internalType": "bool"
          },
          {
            "name": "preventOperatorUpdatingMetadata",
            "type": "bool",
            "internalType": "bool"
          },
          {
            "name": "preventOperatorMinting",
            "type": "bool",
            "internalType": "bool"
          },
          {
            "name": "preventOperatorIncreasingDiscountPercent",
            "type": "bool",
            "internalType": "bool"
          }
        ]
      }
    ],
    "stateMutability": "pure"
  },
  {
    "type": "error",
    "name": "PluginDeployer_NoMachine",
    "inputs": []
  },
  {
    "type": "error",
    "name": "PluginDeployer_NoStartTime",
    "inputs": []
  },
  {
    "type": "error",
    "name": "PluginDeployer_RoutesExceedKeep",
    "inputs": [
      {
        "name": "totalPercent",
        "type": "uint256",
        "internalType": "uint256"
      }
    ]
  }
] as const;
